sudo: required
dist: xenial
language: c
compiler:
  - clang
  - gcc
cache: ccache

before_install:
  - curl http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_16.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_16.04/ /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y -qq cmake nasm gettext libjson-c-dev libgtk-3-dev libncursesw5-dev libcpuid-dev libpci-dev libprocps-dev libarchive-dev libgtk-3-0 libncursesw5 libcpuid14 libpci3 libprocps4
before_script:
  - mkdir -p build1 build2
  - cd "$TRAVIS_BUILD_DIR/build1" && cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GTK=0 -DCMAKE_INSTALL_PREFIX=/usr ..
  - cd "$TRAVIS_BUILD_DIR/build2" && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..

script:
  - cd "$TRAVIS_BUILD_DIR/build1" && make -j$(nproc) && sudo make -j$(nproc) install
  - cd "$TRAVIS_BUILD_DIR/build2" && make -j$(nproc) && make DESTDIR=$(readlink -f appdir) -j$(nproc) install
after_success:
  - cd "$TRAVIS_BUILD_DIR/build1" && make test && sudo CPUX_BCLK=100 cpu-x --issue-fmt
  - cat /tmp/cpu-x.log
  - cat /tmp/cpu-x-daemon.log
  - cd "$TRAVIS_BUILD_DIR/build2" && "$TRAVIS_BUILD_DIR/scripts/build_appimage.sh" appdir

notifications:
  slack:
    on_success: change
    on_failure: always
