language: c

services:
  - docker

env: CPUX_BCLK=100

matrix:
  include:
    - env: ARCH=x86_64 DOCKER_IMAGE=ubuntu/16.04

install:
  - cat /etc/os-release
  - sudo apt-get update
  - sudo apt-get install -y nasm gettext libjson-c-dev libncursesw5-dev libpci-dev libprocps-dev libarchive-dev libncursesw5 libpci3 libprocps4

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GTK=0 -DCMAKE_INSTALL_PREFIX=/usr ..

script:
  - make -j$(nproc)

after_success:
  - sudo make -j$(nproc) install
  - sudo cpu-x --issue-fmt

branches:
  except:
    -  # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
